- name: play level variables
  hosts: local
  connections: local
  vars:
    COURSE: "DevOps with AWS"
    DURATION: "140HRS"
    TRAINER: "Sivakumar Reddy"
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "Course is: {{COURSE}}, Trainer is: {{TRAINER}}"